"""empty message

Revision ID: 02214be2a2e8
Revises: 26d63c6fd573
Create Date: 2023-01-17 17:18:12.132467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02214be2a2e8'
down_revision = '26d63c6fd573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
