"""empty message

Revision ID: 3ac998a3a221
Revises: 02214be2a2e8
Create Date: 2023-01-18 21:13:51.539453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ac998a3a221'
down_revision = '02214be2a2e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('team_city_index', table_name='teams')
    op.drop_index('team_color_index', table_name='teams')
    op.drop_index('team_losses_b_tree_index', table_name='teams')
    op.drop_index('team_state_index', table_name='teams')
    op.drop_index('team_ties_b_tree_index', table_name='teams')
    op.drop_index('team_wins_b_tree_index', table_name='teams')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('team_wins_b_tree_index', 'teams', ['wins'], unique=False)
    op.create_index('team_ties_b_tree_index', 'teams', ['ties'], unique=False)
    op.create_index('team_state_index', 'teams', ['state'], unique=False)
    op.create_index('team_losses_b_tree_index', 'teams', ['losses'], unique=False)
    op.create_index('team_color_index', 'teams', ['home_color'], unique=False)
    op.create_index('team_city_index', 'teams', ['city'], unique=False)
    # ### end Alembic commands ###
